global using Xunit;
global using AutoFixture;
global using Ip2Location.Business.Models;
global using Ip2Location.Business.Services;
global using Ip2Location.Business.Services.Interfaces;
global using Microsoft.Extensions.Options;
global using Moq;
global using OneOf;
global using Ip2Location.Domain.Models;